---
name: PR
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3
      - name: Setup Python
        uses: action/setup-python@v4
        with:
          python-version: 3.9
      - name: Run Python script
        run: |
          echo hello_world.py
          python hello_world.py

#bdh  
#============= Jobs End ===================
